// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission_six_movie_db.Models;

namespace mission_six_movie_db.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    partial class MovieFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission_six_movie_db.Models.Category", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CatId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CatId = 1,
                            CategoryName = "Disney"
                        },
                        new
                        {
                            CatId = 2,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CatId = 3,
                            CategoryName = "Fantasy"
                        });
                });

            modelBuilder.Entity("mission_six_movie_db.Models.MovieFormResponse", b =>
                {
                    b.Property<int>("MovieFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieFormId");

                    b.HasIndex("CategoryId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieFormId = 1,
                            CategoryId = 1,
                            Director = "Mark Dindal",
                            Edited = false,
                            Notes = "World's best movie",
                            Rating = "G",
                            Title = "Emperor's New Groove",
                            Year = 2000
                        },
                        new
                        {
                            MovieFormId = 2,
                            CategoryId = 2,
                            Director = "Jonathan Lynn",
                            Edited = false,
                            Rating = "R",
                            Title = "My Cousin Vinny",
                            Year = 1992
                        },
                        new
                        {
                            MovieFormId = 3,
                            CategoryId = 3,
                            Director = "Hayao Miyazaki",
                            Edited = false,
                            Rating = "G",
                            Title = "My Neighbor Totoro",
                            Year = 1988
                        });
                });

            modelBuilder.Entity("mission_six_movie_db.Models.MovieFormResponse", b =>
                {
                    b.HasOne("mission_six_movie_db.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
